global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: spanish-verb-api
    metrics_path: /metrics
    static_configs:
      - targets: ['spanish-verb-api:3000']
        labels:
          service: spanish-verb-api
          env: dev
